[env:esp32-devkit]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
upload_protocol = esptool
monitor_port=/dev/ttyUSB0
monitor_speed = 115200
lib_deps =
    grt_decode
build_flags = 
    -DCORE_DEBUG_LEVEL=0
